version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static/uploads:/app/static/uploads
    environment:
      - SESSION_SECRET=your-secure-secret-key
      - DATABASE_URL=sqlite:///donations.db
